server:
  port: 8081


app:
  kafka: true
  manager-url: http://localhost:8080

spring:
  kafka:
    consumer:
      group-id: workers
      enable-auto-commit: false
    listener:
      ack-mode: manual_immediate
